import "./src/styles/styles.scss"
import "jquery-slim/dist/jquery.slim.min.js"
// import "./src/assets/js/jquery-slim.min.js"
import "popper.js/dist/popper.min.js"
import "bootstrap/dist/js/bootstrap.min.js"